### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by Pinox** [jsakamoto/Toolbelt.Blazor.ViewTransition#1]
Great work!! Luv this.

Will fade in and out also work with Blazor popups as below ?

![Popups](https://github.com/jsakamoto/Toolbelt.Blazor.ViewTransition/assets/5297255/682d979e-9ca6-4786-87e6-7907fe584e4b)

Is this API also working in Blazor Server ?

**Comment by jsakamoto** [comment]
Hi @Pinox,

> Will fade in and out also work with Blazor popups as below ?

I'm not so sure what is the "Blazor popups" you said, but anyway, the page transition effect this library provided comes from the web browser's "Transition View" API. Therefore, it depends on whether the "Blazor popup" can work together with the "Transition View" API.

This library does only organizes to make the rendering process of Blazor's pages happen inside the `document.startViewTransition()` method invoking.

See also:
- https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API
- https://developer.chrome.com/docs/web-platform/view-transitions/

> Is this API also working in Blazor Server ?

Yes it is. The sample code is here: [📦BlazorServerApp1.zip](https://github.com/jsakamoto/Toolbelt.Blazor.ViewTransition/files/13227254/BlazorServerApp1.zip)

**Comment by Pinox** [comment]
Thanks @jsakamoto  Sorry popups is a bit vague.  I normally use Mudblazor drawer function but will check in that repo if something like this API is supported.

https://mudblazor.com/components/drawer#variants-persistent

**Comment by neozhu** [comment]
in my tested, it's not working in InteractiveServerRenderMode at .net 8. 
I don't know why

**Comment by Pinox** [comment]
@neozhu , the Blazor Server sample you send do work in Blazor Server but that is with just changing the TFM to net8.0.

I have not checked out if you use the .net 8 web template where you then specify the InteractiveServerRenderMode.  In my mind it should work when you specify the InteractiveServerRenderMode on the global (router) level as the standard .net 8 web template default to stream rendering I think.

**Comment by jsakamoto** [comment]
Hi everyone,

> I have not checked out if you use the .net 8 web template

There is no reason for the "Blazor View Transition" not to work with a Blazor app in .NET 8 with interactivity.

I attached two sample codes below to prove it. One is a Blazor app with interactive mode = Server, and the other is one with interactive mode = Auto.

- [📦Blazor8ServerApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.ViewTransition/files/13804696/Blazor8ServerApp.zip)
- [📦Blazor8AutoApp.zip](https://github.com/jsakamoto/Toolbelt.Blazor.ViewTransition/files/13804697/Blazor8AutoApp.zip)

The one important point is that you have to configure your Blazor app to make the "ViewTransitionRouter" component run in any interactivity mode, not a Static Server-Side Render mode. As long as you do that, the "ViewTransitionRouter" must work as you expected.
